---
- name: Install docker from Binary package
  hosts: docker
  tasks:
    - name: add a group for docker
      group:
        name: docker
        state: present
        system: yes
    - name: Copy file and change permissions
      copy:
        src: "{{ item }}"
        dest: /usr/bin/
        mode: '0755'
      with_fileglob:
        - ~/docker/docker/*
    - name: Copy file and change permissions
      copy:
        src: "{{ item }}"
        dest: /lib/systemd/system/
        mode: '0644'
      with_fileglob:
        - ~/docker/services/*
    - name: reload systemd
      shell: |
        systemctl daemon-reload
    - name: start service with os
      systemd:
        name: docker
        state: started
        enabled: yes
