---
- name: Change /etc/hosts file
  hosts: all
  tasks:
    - name: back old hosts file
      copy:
        src: /etc/hosts
        dest: /etc/hosts_back
    - name: edit /etc/hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts
