---
- name: Install kubeadm, kubelet and kubectl
  hosts: all
  tasks:
    - name: Install precondition packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
    - name: Add source key
      apt_key:
        url: "https://mirrors.aliyun.com/kubernetes/apt/doc/apt-key.gpg"
        state: present
    - name: Add source address
      apt_repository:
        repo: 'deb https://mirrors.aliyun.com/kubernetes/apt/ kubernetes-xenial main'
        state: present
        filename: kubernetes
    - name: Install kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present
    - name: Start kubelet service
      service:
        name: kubelet
        state: started
        enabled: yes

- name: Initialize master
  hosts: master
  tasks:
    - name: Copy configure file
      template:
        src: kubeadm.j2
        dest: /tmp/kubeadm.yaml
    - name: Initialize master
      shell: kubeadm init --config /tmp/kubeadm.yaml
      register: shell_result
    - debug:
        var: shell_result
    - name: shell commands
      shell: mkdir -p $HOME/.kube && sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
    - name: Download calico
      get_url:
        url: https://docs.projectcalico.org/v3.20/manifests/calico.yaml 
        dest: /tmp/calico.yaml
    - name: Configure network plug-in
      shell: kubectl create -f /tmp/calico.yaml
 
